name: pipeline

env:
  TEST_COVERAGE_THRESHOLD: 100

on:
  push:
    branches:
      - "*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: 'install uv'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: install requirements
      run: ./helper.sh reqs
    - name: "run SAST test (bandit)"
      run: ./helper.sh sast_check
    - name: "run SCA test (safety)"
      run: ./helper.sh sca_check
      env:
        SAFETY_KEY: ${{ secrets.SAFETY_KEY }} 
    - name: check code linting
      run: ./helper.sh linter_check  
    - name: run unit tests
      run: ./helper.sh test
    - name: check coverage
      run: ./helper.sh test_coverage_check $TEST_COVERAGE_THRESHOLD
    - name: generate coverage badge
      run: |
        coverage-badge -o coverage.svg -f && \
          git config --local user.email "action@github.com" && \
          git config --local user.name "GitHub Action" && \
          git add coverage.svg && \
          git commit -m "Update coverage badge" || exit 0 && \
          git push
    - name: build
      run: ./helper.sh build
    - name: publish
      run: |
        if [[ ${{ github.ref }} =~ refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          ./helper.sh publish
        else
          echo "Invalid semver tag"
        fi
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
